#!/bin/bash
yum install -y httpd
if [ -x "$(command -v yum)" ]; then
    sudo yum install -y <packages>
elif [ -x "$(command -v apt-get)" ]; then
    sudo apt-get update
    sudo apt-get install -y <packages>
else
    echo "No supported package manager found!"
    exit 1
fi

